DESC MyTable10;


-- SHOW CREATE TABLE : 테이블 생성 명령 보기
SHOW CREATE TABLE MyTable10;
CREATE TABLE `MyTable11` (
   `Name` varchar(10) DEFAULT NULL,
   `Price` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;
DESC MyTable10;
DESC MyTable10;

--
CREATE TABLE MyTable12 AS SELECT * FROM MyTable10;
DESC MyTable12;
SELECT * FROM MyTable12;