DESC MyTable13;
-- MODIFY COLUMN : 컬럼 타입 변경
ALTER TABLE MyTable13
MODIFY COLUMN col20 VARCHAR(40);

SELECT * FROM MyTable13;

ALTER TABLE MyTable13
MODIFY COLUMN col13 VARCHAR(3); -- 위험

-- 연습) MyTable13에서 아무 컬럼이나 타입 변경
ALTER TABLE MyTable13
MODIFY COLUMN col4 INT;

ALTER TABLE MyTable13
MODIFY COLUMN col8 VARCHAR(9) FIRST;
ALTER TABLE MyTable13
MODIFY COLUMN col8 VARCHAR(9) AFTER col6;

-- 연습) MyTable13의 아무 컬럼의 위치 변경
ALTER TABLE MyTable13
MODIFY COLUMN col7 VARCHAR(7) AFTER col9;